version: '3.7'
services:
  mongo:
    image: "mongo"
    restart: always
    # ports: 
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=jbjb123
    command: 
      - --smallfiles


  mongo-express:
    image: "mongo-express"
    depends_on:
      - mongo
    restart: always
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=jbjb123

  ml_rest:
    image: "ml_rest"
    ports:
      - 8123:8123

  ml_webapp:
    image: "docker/bach.project/mlwebapp"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - ml_rest